version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}  
    depends_on:
      - mongo
    networks:
      - shop-nexus-core
  
  product-service:
    build: ./product-service
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - shop-nexus-core

  order-service:
    build: ./order-service
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - RABBITMQ_URI=${RABBITMQ_URI} 
      - JWT_SECRET=${JWT_SECRET}
      - PRODUCT_SERVICE_URL=${PRODUCT_SERVICE_URL}
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - shop-nexus-core

  recommendation-service:
    build: ./recommendation-service
    ports:
      - "8003:8003"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - DB_NAME=${DB_NAME}
      - API_KEYS=${API_KEYS}
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - shop-nexus-core

  notification-service:
    build: ./notification-service
    ports:
      - "8004:8004"
    environment:
      - RABBITMQ_URI=${RABBITMQ_URI}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shop-nexus-core
    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - shop-nexus-core

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shop-nexus-core
  
networks:
  shop-nexus-core:
    driver: bridge

volumes:
  mongo-data: