version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}  
    depends_on:
      - mongo
  
  product-service:
    build: ./product-service
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongo

  recommendation-service:
    build: ./recommendation-service
    ports:
      - "8003:8003"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongo
      - rabbitmq

  notification-service:
    build: ./notification-service
    ports:
      - "8004:8004"
    environment:
      - RABBITMQ_URI=${RABBITMQ_URI}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - rabbitmq
    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Puerto AMQP
      - "15672:15672" # Interfaz de gestión (opcional)
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: